config/routes.rb
Rails.application.routes.draw do

  root 'paginas#home'
  get 'cadastre'=> 'usuarios#new'
  get 'sobre' => 'paginas#sobre'

  resources :usuarios
  resources :colaboradores

end

app/models/colaborador.rb
class Colaborador < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base

    validates :nome, presence: true, length: {maximum: 50}
    validates :email, presence: true, length: {maximum: 255}

    has_secure_password
    validates :password, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/colaboradores_controller.rb
class ColaboradoresController < ApplicationController
  before_action :set_colaborador, only: [:show, :edit, :update, :destroy]

  # GET /colaboradores
  # GET /colaboradores.json
  def index
    @colaboradores = Colaborador.all
  end

  # GET /colaboradores/1
  # GET /colaboradores/1.json
  def show
  end

  # GET /colaboradores/new
  def new
    @colaborador = Colaborador.new
  end

  # GET /colaboradores/1/edit
  def edit
  end

  # POST /colaboradores
  # POST /colaboradores.json
  def create
    @colaborador = Colaborador.new(colaborador_params)

    respond_to do |format|
      if @colaborador.save
        format.html { redirect_to @colaborador, notice: 'Colaborador was successfully created.' }
        format.json { render :show, status: :created, location: @colaborador }
      else
        format.html { render :new }
        format.json { render json: @colaborador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colaboradores/1
  # PATCH/PUT /colaboradores/1.json
  def update
    respond_to do |format|
      if @colaborador.update(colaborador_params)
        format.html { redirect_to @colaborador, notice: 'Colaborador was successfully updated.' }
        format.json { render :show, status: :ok, location: @colaborador }
      else
        format.html { render :edit }
        format.json { render json: @colaborador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colaboradores/1
  # DELETE /colaboradores/1.json
  def destroy
    @colaborador.destroy
    respond_to do |format|
      format.html { redirect_to colaboradores_url, notice: 'Colaborador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colaborador
      @colaborador = Colaborador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def colaborador_params
      params.require(:colaborador).permit(:nome, :matricula, :contrato, :salario)
    end
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  def home
  end

  def sobre
  end
end

app/controllers/sessoes_controller.rb
class SessoesController < ApplicationController
  def new
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController

  def show
      @usuario = Usuario.find(params[:id])
  end

  def new
      @usuario = Usuario.new
  end

  def create
    @usuario = Usuario.new(usuario_params)
        if @usuario.save
        flash[:success] = "Novo usuário cadastrado com sucesso!"
        redirect_to @usuario
        # Handle a successful save.
        else
        render 'new'
        end
    end


  private
     def usuario_params
       params.require(:usuario).permit(:nome, :email, :password,
       :password_confirmation)
     end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colaboradores_helper.rb
module ColaboradoresHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(usuario)
  gravatar_id = Digest::MD5::hexdigest(usuario.email.downcase)
  gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
  image_tag(gravatar_url, alt: usuario.nome, class: "gravatar")
  end

end

app/views/colaboradores/_form.html.erb
<%= form_for(@colaborador) do |f| %>
  <% if @colaborador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@colaborador.errors.count, "error") %> prohibited this colaborador from being saved:</h2>

      <ul>
      <% @colaborador.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :matricula %><br>
    <%= f.text_field :matricula %>
  </div>
  <div class="field">
    <%= f.label :contrato %><br>
    <%= f.text_field :contrato %>
  </div>
  <div class="field">
    <%= f.label :salario %><br>
    <%= f.text_field :salario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colaboradores/edit.html.erb
<h1>Editing Colaborador</h1>

<%= render 'form' %>

<%= link_to 'Show', @colaborador %> |
<%= link_to 'Back', colaboradores_path %>

app/views/colaboradores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Colaboradores</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Matricula</th>
      <th>Contrato</th>
      <th>Salario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colaboradores.each do |colaborador| %>
      <tr>
        <td><%= colaborador.nome %></td>
        <td><%= colaborador.matricula %></td>
        <td><%= colaborador.contrato %></td>
        <td><%= colaborador.salario %></td>
        <td><%= link_to 'Show', colaborador %></td>
        <td><%= link_to 'Edit', edit_colaborador_path(colaborador) %></td>
        <td><%= link_to 'Destroy', colaborador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Colaborador', new_colaborador_path %>

app/views/colaboradores/new.html.erb
<h1>New Colaborador</h1>

<%= render 'form' %>

<%= link_to 'Back', colaboradores_path %>

app/views/colaboradores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @colaborador.nome %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @colaborador.matricula %>
</p>

<p>
  <strong>Contrato:</strong>
  <%= @colaborador.contrato %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @colaborador.salario %>
</p>

<%= link_to 'Edit', edit_colaborador_path(@colaborador) %> |
<%= link_to 'Back', colaboradores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%AMEE%></title>
      <%= stylesheet_link_tag 'application', media: 'all',
      'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
      <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
      <%= link_to "AMEE", '#', id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home",root_path %></li>
                <li><%= link_to "Sobre",sobre_path %></li>
                <li><%= link_to "Log in", '#' %></li>
           </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/paginas/home.html.erb
<div class="center jumbotron">

    <h1>Área de Microeletrônica e Eletrônica Embarcada - SENAI - CIMATEC</h1>
    <h2>
        Sistema de gerenciamento da AMEE
    </h2>
    <%= link_to "Cadastre-se", cadastre_path, class: "btn btn-lg btn-primary" %>

</div>

app/views/paginas/sobre.html.erb
<h1>Paginas#sobre</h1>
<p>Find me in app/views/paginas/sobre.html.erb</p>

app/views/usuarios/new.html.erb
<% provide(:title, 'Adicionando novo Usuário') %>
    <h1>Adicionando novo Usuário</h1>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
            <%= form_for(@usuario) do |f| %>
                <%= f.label :nome %>
                <%= f.text_field :nome %>
                <%= f.label :email %>
                <%= f.email_field :email %>
                <%= f.label :password %>
                <%= f.password_field :password %>
                <%= f.label :password_confirmation, "Confirmação" %>
                <%= f.password_field :password_confirmation %>
                <%= f.submit "Criando novo Usuário", class: "btn btn-primary" %>
            <% end %>
          </div>
      </div>

app/views/usuarios/show.html.erb
<% provide(:title, @usuario.nome) %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1>
        <%= gravatar_for @usuario %>
        <%= @usuario.nome %>
        </h1>
      </section>
    </aside>
  </div>